// 15 mashups Pokémon — version finale validée
// Format: type officiel du Pokémon de base (Sun & Moon TCG style)
// Conventions:
//   - "L'Adversaire" est utilisé partout (vocabulaire officiel Pokémon TCG)
//   - "Ce Pokémon" = le Pokémon attaquant
//   - Indices construits du plus large au plus précis pour faire deviner Pokémon → nom mashup
//   - Indices neutres en genre (pas de il/elle direct)

module.exports = [
  // =========== NICO ===========
  {
    num: "01",
    pokemonBase: "Machoke",
    nomMashup: "Nicogneur",
    target: "Nico",
    type: "fighting",
    stage: "Stage 1",
    evolvesFrom: "Machop",
    hp: 100,
    pokedexNumber: "0067",
    species: "Crossfit",
    height: "5'09\"",
    weight: "85 kg",
    attackCost: ["fighting", "fighting", "colorless"],
    attackName: "WOD du Dimanche",
    attackDamage: 80,
    attackText: "Inflige 20 dégâts de plus pour chaque shaker de whey attaché.",
    weakness: { type: "psychic", value: "+20" },
    retreat: 2,
    flavorText: "Il s'est mis au CrossFit pour fondre avant le mariage. Sa whey n'est jamais bien loin.",
    indices: [
      "Pratique un sport intense",
      "Donne tout pendant chaque séance, jusqu'à l'épuisement",
      "Se complémente, il faut garder les muscles"
    ]
  },
  {
    num: "02",
    pokemonBase: "Ponyta",
    nomMashup: "Pimentita",
    target: "Nico",
    type: "fire",
    stage: "Basic",
    hp: 70,
    pokedexNumber: "0077",
    species: "Sauce Piquante",
    height: "3'03\"",
    weight: "30 kg",
    attackCost: ["fire", "fire"],
    attackName: "Carolina Reaper",
    attackDamage: 60,
    attackText: "L'Adversaire est désormais Brûlé. Lait fortement recommandé.",
    weakness: { type: "water", value: "+20" },
    retreat: 1,
    flavorText: "Sa crinière s'enflamme à chaque bouchée. Aucun palais humain ne peut suivre sa tolérance Scoville.",
    indices: [
      "Galope quand il y a du feu sous les sabots",
      "Adore la chaleur, encore plus si elle pique",
      "A développé une tolérance Scoville hors-norme"
    ]
  },
  {
    num: "03",
    pokemonBase: "Magneton",
    nomMashup: "Dispersaton",
    target: "Nico",
    type: "lightning",
    stage: "Stage 1",
    evolvesFrom: "Magnemite",
    hp: 90,
    pokedexNumber: "0082",
    species: "Hyperactif",
    height: "3'03\"",
    weight: "60 kg",
    attackCost: ["lightning", "lightning", "colorless"],
    attackName: "Dispersion Totale",
    attackDamage: 70,
    attackText: "Ce Pokémon attaque dans 3 directions en même temps. Aucune défausse possible.",
    weakness: { type: "fighting", value: "+20" },
    retreat: 2,
    flavorText: "Trois cerveaux tournent en parallèle 24h/24 : Kings & Lords, AI et basket. Seule Claire peut le rappeler à l'ordre.",
    indices: [
      "Plusieurs cerveaux qui tournent en parallèle",
      "Cultive toutes les passions à la fois",
      "Hyperactif, ne sait pas s'arrêter"
    ]
  },
  {
    num: "04",
    pokemonBase: "Mr. Mime",
    nomMashup: "Mr. Daddy",
    target: "Nico",
    type: "psychic",
    stage: "Basic",
    hp: 90,
    pokedexNumber: "0122",
    species: "Cringe-Mime",
    height: "4'03\"",
    weight: "55 kg",
    attackCost: ["psychic", "colorless"],
    attackName: "Jeu de Mot Cringe",
    attackDamage: 40,
    attackText: "L'Adversaire est déstabilisé. +20 s'il est bon public.",
    weakness: { type: "psychic", value: "+20" },
    retreat: 1,
    flavorText: "« Vietnam ta touillette » — sa blague signature. Ça reste dans la tête.",
    indices: [
      "Coincé dans une cage qui n'existe pas",
      "Place une vanne à chaque ouverture",
      "Pro des blagues de papa"
    ]
  },
  {
    num: "05",
    pokemonBase: "Smoochum",
    nomMashup: "Nipoutou",
    target: "Nico",
    type: "psychic",
    stage: "Basic",
    hp: 80,
    pokedexNumber: "0238",
    species: "Designer",
    height: "1'04\"",
    weight: "13 kg",
    attackCost: ["psychic", "colorless"],
    attackName: "Coupe Yolo",
    attackDamage: 30,
    attackText: "L'Adversaire est aveuglé. Qui est ce Pokémon en face de moi ?",
    weakness: { type: "psychic", value: "+20" },
    retreat: 2,
    flavorText: "Méconnaissable tous les 4 mois, à chaque passage chez le coiffeur-barbier.",
    indices: [
      "Aime les bisous",
      "T'as essayé l'argot ?",
      "La coupe est en évolution"
    ]
  },
  {
    num: "06",
    pokemonBase: "Snorlax",
    nomMashup: "Grignoflex",
    target: "Nico",
    type: "colorless",
    stage: "Basic",
    hp: 150,
    pokedexNumber: "0143",
    species: "Grignoteur",
    height: "6'11\"",
    weight: "90 kg",
    attackCost: ["colorless", "colorless", "colorless"],
    attackName: "Frigo Ouvert",
    attackDamage: 60,
    attackText: "Pioche 2 collations. Divisés par deux si Claire le surprend la main dans le sac.",
    weakness: { type: "fighting", value: "+20" },
    retreat: 4,
    flavorText: "Grignote avec gourmandise, a du mal à s'arrêter. Heureusement, les WOD le sauvent.",
    indices: [
      "Gourmand",
      "Ronfle",
      "Inarrêtable"
    ]
  },
  {
    num: "07",
    pokemonBase: "Muk",
    nomMashup: "Grostasdetrucs",
    target: "Nico",
    type: "darkness",
    stage: "Stage 1",
    evolvesFrom: "Grimer",
    hp: 130,
    pokedexNumber: "0089",
    species: "Compulsif",
    height: "3'11\"",
    weight: "100 kg",
    attackCost: ["darkness", "darkness", "colorless"],
    attackName: "Black Friday",
    attackDamage: 70,
    attackText: "Chaque carte Pokémon, sauce piquante et objet collectionné ajoute +10.",
    weakness: { type: "fighting", value: "+20" },
    retreat: 3,
    flavorText: "Accumule plus vite qu'il ne consomme. Ses placards sont un musée de lubies passées.",
    indices: [
      "Aime collectionner",
      "Accumule, jusqu'à déborder",
      "Il n'y a bientôt plus d'espace de stockage disponible"
    ]
  },

  // =========== CLAIRE ===========
  {
    num: "08",
    pokemonBase: "Scyther",
    nomMashup: "Inseclairteur",
    target: "Claire",
    type: "grass",
    stage: "Basic",
    hp: 90,
    pokedexNumber: "0123",
    species: "Main Verte",
    height: "4'11\"",
    weight: "56 kg",
    attackCost: ["grass", "colorless"],
    attackName: "Pouce Vert",
    attackDamage: 50,
    attackText: "Plante 3 fleurs à longue tige sur le terrain. +10 par fleur attachée.",
    weakness: { type: "fire", value: "+20" },
    retreat: 1,
    flavorText: "A déjà préparé des dizaines de pots de petites fleurs pour le mariage. Son bananier prospère, ses nénuphars aussi.",
    indices: [
      "Le monde de l'infiniment petit",
      "Peut couper tout ce qui dépasse pour relancer la croissance",
      "L'outil indispensable quand on a la main verte"
    ]
  },
  {
    num: "09",
    pokemonBase: "Butterfree",
    nomMashup: "Brocantusion",
    target: "Claire",
    type: "grass",
    stage: "Stage 2",
    evolvesFrom: "Metapod",
    hp: 120,
    pokedexNumber: "0012",
    species: "Chineuse",
    height: "3'07\"",
    weight: "32 kg",
    attackCost: ["grass", "grass", "colorless"],
    attackName: "Trouvaille Brocante",
    attackDamage: 70,
    attackText: "Détecte une pièce rare à 50 mètres. Cadre Ikea : aucun effet.",
    weakness: { type: "fire", value: "+20" },
    retreat: 1,
    flavorText: "Son cœur s'emballe à chaque trouvaille. Les vide-greniers du dimanche sont son terrain de jeu préféré.",
    indices: [
      "Ce n'est pas une illusion",
      "Papillonne d'objet en objet",
      "Passion brocante"
    ]
  },
  {
    num: "10",
    pokemonBase: "Omanyte",
    nomMashup: "Antiquitoss",
    target: "Claire",
    type: "water",
    stage: "Basic",
    hp: 70,
    pokedexNumber: "0138",
    species: "Antiquaire",
    height: "1'04\"",
    weight: "8 kg",
    attackCost: ["water", "colorless"],
    attackName: "Attaque Surprise",
    attackDamage: 40,
    attackText: "Plus c'est vieux, plus ça frappe fort. +20 par année d'ancienneté.",
    weakness: { type: "grass", value: "+20" },
    retreat: 1,
    flavorText: "Il ne manque que la piscine. En attendant, les distributeurs à boules suffisent à la remplir.",
    indices: [
      "Mimi comme tout",
      "D'une autre époque, plus c'est ancien mieux c'est",
      "Obsession particulière : les boules"
    ]
  },
  {
    num: "11",
    pokemonBase: "Togepi",
    nomMashup: "Togeclaire",
    target: "Claire",
    type: "fairy",
    stage: "Basic",
    hp: 60,
    pokedexNumber: "0175",
    species: "Multi-Passions",
    height: "1'00\"",
    weight: "2 kg",
    attackCost: ["fairy"],
    attackName: "« Alors ? »",
    attackDamage: 30,
    attackText: "Regard insistant et plein de malice. « Bon, quand est-ce que vous faites des enfants ? » L'Adversaire est désormais Confus. +20 s'il est en couple.",
    weakness: { type: "metal", value: "+10" },
    retreat: 1,
    flavorText: "Éclot en révélant une nouvelle passion à chaque saison : plantes, insectes, yoga, déco, antiquités…",
    indices: [
      "Plein de surprises, on ne sait jamais ce qui va sortir de la coquille",
      "12 passions en parallèle",
      "Veut des bébés, mais surtout dans son entourage"
    ]
  },
  {
    num: "12",
    pokemonBase: "Ledyba",
    nomMashup: "Coxyclaire",
    target: "Claire",
    type: "grass",
    stage: "Basic",
    hp: 50,
    pokedexNumber: "0165",
    species: "Maman-Coccinelle",
    height: "3'03\"",
    weight: "11 kg",
    attackCost: ["grass"],
    attackName: "Pull Moche",
    attackDamage: 30,
    attackText: "L'Adversaire est désormais vêtu d'un pull moche de Noël devant tous les autres en costards. Il est Confus.",
    weakness: { type: "fire", value: "+20" },
    retreat: 1,
    flavorText: "Avec Nico, ils ont accueilli tout le monde en pulls moches pour les emmener à leur vrai mariage à la mairie. Iconique.",
    indices: [
      "Petite bête mignonne",
      "On peut deviner son âge en comptant ses points",
      "Pro de l'organisation de Secret Santa"
    ]
  },
  {
    num: "13",
    pokemonBase: "Alakazam",
    nomMashup: "Alakaclaire",
    target: "Claire",
    type: "psychic",
    stage: "Stage 2",
    evolvesFrom: "Kadabra",
    hp: 130,
    pokedexNumber: "0065",
    species: "Stratège",
    height: "4'11\"",
    weight: "48 kg",
    attackCost: ["psychic", "colorless", "colorless"],
    attackName: "Calcul Mental",
    attackDamage: 60,
    attackText: "Anticipe 3 coups d'avance. Connaît tous les gossips avant tout le monde. +30 si jeu de société en cours.",
    weakness: { type: "psychic", value: "+20" },
    retreat: 2,
    flavorText: "QI redoutable, mémoire des ragots infaillible. À Noël, elle a déjà gagné le Time's Up avant la 2e manche.",
    indices: [
      "Comme un air de magie",
      "Toujours 3 coups d'avance",
      "Surnommé l'architecte"
    ]
  },
  {
    num: "14",
    pokemonBase: "Hitmonlee",
    nomMashup: "Kiclaire",
    target: "Claire",
    type: "fighting",
    stage: "Basic",
    hp: 100,
    pokedexNumber: "0106",
    species: "Yoga Master",
    height: "5'11\"",
    weight: "55 kg",
    attackCost: ["fighting", "fighting"],
    attackName: "Posture du Pigeon Royal",
    attackDamage: 70,
    attackText: "Pose impossible. L'Adversaire est désormais Étonné. +20 si l'Adversaire est moins souple.",
    weakness: { type: "psychic", value: "+20" },
    retreat: 2,
    flavorText: "Enchaîne les postures impossibles avec un calme déconcertant. Personne ne comprend comment elle fait.",
    indices: [
      "Un coup de pied légendaire",
      "Souplesse hors du commun",
      "Yoga power !"
    ]
  },

  // =========== FINALE FAMILLE ===========
  {
    num: "15",
    pokemonBase: "Famille Nidoran",
    nomMashup: "La Famille Nido",
    target: "Couple+Filles",
    type: "fairy",
    stage: "Family",
    hp: 999,
    pokedexNumber: "0033",
    species: "Mariage",
    height: "—",
    weight: "—",
    attackCost: ["fairy", "fairy", "colorless"],
    attackName: "Oui, Je Le Veux",
    attackDamage: 1000,
    attackText: "Évolution finale du couple Pokémon canonique. Cap sur Domont, en Tesla Model Y, avec deux Nidoran à l'arrière.",
    weakness: { type: "psychic", value: "—" },
    retreat: 0,
    flavorText: "Ensemble depuis 14 ans, Pomme (5) et Dune (4) en évolutions. Cette année : forme finale.",
    indices: [
      "Un troupeau, comme les Addams",
      "À des cornes préhistoriques",
      "Deux parents évolués au maximum, deux petits encore à leur forme de base"
    ]
  }
];
